const MUTATIONS_TYPES = Object.freeze({
  SET_UNIT_COLLECTION: `SET_UNIT_COLLECTION`,
  SET_UNIT: `SET_UNIT`,
  SET_TOTAL_ITEMS: `SET_TOTAL_ITEMS`,
  SET_TOTAL_PAGES: `SET_TOTAL_PAGES`,
  SET_CURRENT_PAGE: `SET_CURRENT_PAGE`
});

export default MUTATIONS_TYPES;
