const MUTATIONS_TYPES = Object.freeze({
  SET_TEMPLATE_COLLECTION: `SET_TEMPLATE_COLLECTION`,
  SET_TEMPLATE: `SET_TEMPLATE`,
  SET_TOTAL_ITEMS: `SET_TOTAL_ITEMS`,
  SET_TOTAL_PAGES: `SET_TOTAL_PAGES`,
  SET_CURRENT_PAGE: `SET_CURRENT_PAGE`
});

export default MUTATIONS_TYPES;
