const MUTATIONS_TYPES = Object.freeze({
  SET_ELEMENT_COLLECTION: `SET_ELEMENT_COLLECTION`,
  SET_ELEMENT: `SET_ELEMENT`,
  SET_TOTAL_ITEMS: `SET_TOTAL_ITEMS`,
  SET_TOTAL_PAGES: `SET_TOTAL_PAGES`,
  SET_CURRENT_PAGE: `SET_CURRENT_PAGE`
});

export default MUTATIONS_TYPES;
