const MUTATIONS_TYPES = Object.freeze({
  SET_LESSON_COLLECTION: `SET_LESSON_COLLECTION`,
  SET_LESSON: `SET_LESSON`,
  SET_TOTAL_ITEMS: `SET_TOTAL_ITEMS`,
  SET_TOTAL_PAGES: `SET_TOTAL_PAGES`,
  SET_CURRENT_PAGE: `SET_CURRENT_PAGE`
});

export default MUTATIONS_TYPES;
