const MUTATIONS_TYPES = Object.freeze({
  SET_COURSE_COLLECTION: `SET_COURSE_COLLECTION`,
  SET_COURSE: `SET_COURSE`,
  SET_TOTAL_ITEMS: `SET_TOTAL_ITEMS`,
  SET_TOTAL_PAGES: `SET_TOTAL_PAGES`,
  SET_CURRENT_PAGE: `SET_CURRENT_PAGE`,
  CLEAR_STATE: `CLEAR_STATE`
});

export default MUTATIONS_TYPES;
