const MUTATIONS_TYPES = Object.freeze({
  SET_CRITERIA_COLLECTION: `SET_CRITERIA_COLLECTION`,
  SET_CRITERIA: `SET_CRITERIA`,
  SET_TOTAL_ITEMS: `SET_TOTAL_ITEMS`,
  SET_TOTAL_PAGES: `SET_TOTAL_PAGES`,
  SET_CURRENT_PAGE: `SET_CURRENT_PAGE`
});

export default MUTATIONS_TYPES;
